name: CI
on:
  push:

jobs:
  apk:
    name: Build Android APKs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
      - run: flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v2
        with:
          name: armeabi-v7a.apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: arm64-v8a.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64.apk
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
